export const PIXELS_API_URL = `https://pixels-node-api.herokuapp.com`;
export const PIXELS_API_VERSION = `1`;

export const GET_INITIAL_INFO = 'GET_INITIAL_INFO';
export const GET_INITIAL_INFO_PENDING = 'GET_INITIAL_INFO_PENDING';
export const GET_INITIAL_INFO_FULFILLED = 'GET_INITIAL_INFO_FULFILLED';
export const GET_INITIAL_INFO_REJECTED = 'GET_INITIAL_INFO_REJECTED';

export const GET_POSTS_BY_TOPIC = 'GET_POSTS_BY_TOPIC';
export const GET_POSTS_BY_TOPIC_PENDING = 'GET_POSTS_BY_TOPIC_PENDING';
export const GET_POSTS_BY_TOPIC_FULFILLED = 'GET_POSTS_BY_TOPIC_FULFILLED';
export const GET_POSTS_BY_TOPIC_REJECTED = 'GET_POSTS_BY_TOPIC_REJECTED';

export const GET_POSTS_BY_USER = 'GET_POSTS_BY_USER';
export const GET_POSTS_BY_USER_PENDING = 'GET_POSTS_BY_USER_PENDING';
export const GET_POSTS_BY_USER_FULFILLED = 'GET_POSTS_BY_USER_FULFILLED';
export const GET_POSTS_BY_USER_REJECTED = 'GET_POSTS_BY_USER_REJECTED';

export const UPDATE_VOTE = 'UPDATE_VOTE';
export const UPDATE_VOTE_PENDING = 'UPDATE_VOTE_PENDING';
export const UPDATE_VOTE_FULFILLED = 'UPDATE_VOTE_FULFILLED';
export const UPDATE_VOTE_REJECTED = 'UPDATE_VOTE_REJECTED';

export const GET_POST = 'GET_POST';
export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';

export const GET_BEST_POST = 'GET_BEST_POST';
export const GET_BEST_POST_PENDING = 'GET_BEST_PENDING';
export const GET_BEST_POST_FULFILLED = 'GET_BEST_POST_FULFILLED';
export const GET_BEST_POST_REJECTED = 'GET_BEST_POST_REJECTED';

export const GET_TOPIC = 'GET_TOPIC';
export const GET_TOPIC_PENDING = 'GET_TOPIC_PENDING';
export const GET_TOPIC_FULFILLED = 'GET_TOPIC_FULFILLED';
export const GET_TOPIC_REJECTED = 'GET_TOPIC_REJECTED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';


export const ADD_POST = 'ADD_POST';
export const ADD_POST_PENDING = 'ADD_POST_PENDING';
export const ADD_POST_FULFILLED = 'ADD_POST_FULFILLED';
export const ADD_POST_REJECTED = 'ADD_POST_REJECTED';
