export const PIXELS_API_URL = `https://pixels-node-api.herokuapp.com`;
export const PIXELS_API_VERSION = `1`;

export const GET_INITIAL_INFO = 'GET_INITIAL_INFO';
export const GET_INITIAL_INFO_PENDING = 'GET_INITIAL_INFO_PENDING';
export const GET_INITIAL_INFO_FULFILLED = 'GET_INITIAL_INFO_FULFILLED';
export const GET_INITIAL_INFO_REJECTED = 'GET_INITIAL_INFO_REJECTED';

export const GET_POSTS_BY_TOPIC = 'GET_POSTS_BY_TOPIC';
export const GET_POSTS_BY_TOPIC_PENDING = 'GET_POSTS_BY_TOPIC_PENDING';
export const GET_POSTS_BY_TOPIC_FULFILLED = 'GET_POSTS_BY_TOPIC_FULFILLED';
export const GET_POSTS_BY_TOPIC_REJECTED = 'GET_POSTS_BY_TOPIC_REJECTED';

// export const GET_POSTS_BY_USER = 'GET_POSTS_BY_USER';
// export const GET_USER_DETAILS = 'GET_USER_DETAILS';
// export const GET_VOTER_INFO = 'GET_VOTER_INFO';
// export const GET_COMMENTS_BY_POST = 'GET_COMMENTS_BY_POST';
